name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLES: true
      DTC_PROJECT_BRANCH: ${{ github.head_ref || github.ref_name }} 
    steps:
      - uses: actions/checkout@v3
      - name: generateSite
        run: cd _documentation && ./dtcw generateSite
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _documentation/build/microsite/output
